language: php
php:
- '7.2'
mysql:
  database: pantheon
  username: pantheon
  encoding: utf8
env:
  global:
  - MOZ_HEADLESS=1
  - SITE_NAME='McWaffleiron'
  - PSITE='mcwaffleiron'
  - PENV='dev'
before_install:
- composer self-update
install:
- composer install
- yarn
notifications:
  email:
    recipients:
    - web@mckenziewagner.com
    on_success: always
    on_failure: change
addons:
  firefox: latest
  chrome: stable
