language: php
php:
- '7.1'
- '7.2'
- nightly
mysql:
  database: pantheon
  username: pantheon
  encoding: utf8
env:
  global:
  - SITE_NAME='McWaffleiron'
  - PSITE='mcwaffleiron'
  - PENV='dev'
  - secure: B5TThln1Z0sJrTcndYPG4vy2wWCx6yZdbWSQht+OhhEabxIoRU58wGaUy9lZeduD9jSU24Jw4kPyurlSUlV+T1S++ikJ9nIHPNJ6U6xWR1lb/2bpkhif4M1X5zc6Lg897J+NCYFKbyRG+tBrPTUhbM7U6fp9QuonyvIbRhSBxe2lpFj1EL2Y5kIrvbz3d42AKK+H5PuT+dWxIJb3WcjnDvN2Vk89WrR4p88QQCbXkAtsR4wWbmoudIEKayzy+hQeks4b0QeUMeLlVl9z7PApx9U95RNoEpOBwocwAhbNpHLWJnj9paMpIqK4CFSlEeOweG2O7OtNwCyCr/u5ih/wF/hC69HXCpbqI/0GRipuyF0jdQgdJb3wGl6Tnw09obOUU0cOs7IaEoIbKmB1HmKuUhP2w0mWpmpdK6EqmpNeSR4LbJyjicjtzzBlAIHCay9ffz1+jo/U2Q+LM3bO+/OThKOBZA6awAu+G/VvxkuBB5QWgJmK6soYIaEE2E/ZmQH618GRolWeUpPNBUCabhNUIDgtlkpDHC1+0vef0sSnNm1RVm2mizkeYT98WFd9HvoQLi9PwlcpwuosrQ3S9hvkXH3b9M9X2WZ4o+Qx/WPmjXiBjNtuXT0OTqQpE9WnT0OXHQDYp3+kqcr+SmoSh4lpIrw0TCRCnf+vlRkIgnuPVqg=
  - secure: ZsYIYDPMpNjPPcY+Q8YPO5tNAo5LskkSnddcfK2o1RqVMoooRCWWQvSVabJsBp9HKWrB8UYekRur0vy2TNMfZtYYX+GCJKLIkt5STKweCx0LetfSIEBNnfChS0hNPk19i6y1VJsRBY8vhYlDLbovkINJNXI9JSJCwFKtHvPz8k0+MlEzqGSv3GUaJ01Ze+U5t+L4f66mB12Ww2zDB/tqdwnfCDZRqg5Ubez/e/qC3o8PA+GhT/93e0mePph9ohbFqY5NNu+5JyS/cgBdxKmxCGSBpByErUcxUkB5CJo23m/e4YIITr52rzQgZ9p9kL9xAhXYtwHyn+5ceJytCNsTzcI7BYa8djQWuoVcCkGrWWHQ/VsqUpqeVP3zopI42fRM+pktFU/Djc2BQNYt84epwD/LINaX+puJOhxOSSGCveOE8cIerHIwezkgnnyGl0ItQ2jFc2E9EBA4JUCLnRBUThRcIkw/aVjhgGCTNyW0qNI+T+YV8MwQc/Jte8G8MTiRkF2+0ct2Y9E53ZnPmh+wddQ/ZvlYRxhAE9Da9zYXl3POexEODoY8dfnnYb4qKSVgTaRA4ypF3dWnvCwSBGc1gUdf7C505+TIAvRQ1C6lb9UU5tXCl+kjozD6id6//iu1LoLcPE978Sx9nwk8A7U/K+fXDGPtpSrOA8t3/fbs+8E=
before_install:
- composer self-update
install:
- composer install
notifications:
  email:
    recipients:
    - web@mckenziewagner.com
    on_success: always
    on_failure: always
