language: php
php:
- '7.0'
- '7.1'
- '7.2'
- nightly
allow_failures:
- php:
  - '7.0'
  - nightly
mysql:
  database: pantheon
  username: pantheon
  encoding: utf8
env:
  global:
  - MOZ_HEADLESS=1
  - SITE_NAME='McWaffleiron'
  - PSITE='mcwaffleiron'
  - PENV='dev'
before_script:
- rackup
- sleep 3
before_install:
- openssl aes-256-cbc -K $encrypted_10d13d6e58a9_key -iv $encrypted_10d13d6e58a9_iv
  -in .env.enc -out .env -d
- composer self-update
install:
- composer install
- yarn
notifications:
  email:
    recipients:
    - web@mckenziewagner.com
    on_success: always
    on_failure: change
addons:
  firefox: latest
  chrome: stable
