language: php
php:
- '7.2'
mysql:
  database: pantheon
  username: pantheon
  encoding: utf8
env:
  global:
  - MOZ_HEADLESS=1
  - SITE_NAME='McWaffleiron'
  - PSITE='mcwaffleiron'
  - PENV='dev'
  - secure: "3UkoFa27iCSDYdYXwk64TVSMvY/X/wNuWP0Ny0n14kkoGvTl6unuHx3zASVD/wRp876MI3MOHHosbmyQOyHV/d500TXEg7fZCIe3Sokszngd3/iREB5Vqjce3sHqlGpmyB2Nv0V2z6+gBP2H5q/DObZztSizMhwEIS8TSGS+5iNUziHJLCu0O1G1SGO+16J7jBw88haWEA0vDb/nXyIer4zaZhxrTaNPIM8ctja6tSTGsXa9MFyxwufdClfALjPkbrTUT/iNOa3Yd7P1rnozXrxTAaVmoLNSuCV8bWP1KOyeIsyWu3j26eYLuZbwJQpJIHwYIU4KHe0tezIRM/45eUeK1v0x5bhJfN0gxxQAIZfmLkOFHuu8bjeZGHcr/E7ypEX5CVm7nnV3on3KMjQjOklC8YnFDYcmSk4sYPsVzC8Y+uLjNbgwXIG5JZcqxH+BqxYQO3Mpsix8CQEuvXekqYmNrlJMUJR8e5PTUb6CS88LZGXJ1AI4XErOnlCbQfAyo/ygEPWzodU2QGnLlFGbEhhAGCEisa0Hn0t+ht/0Sf2xckjd4wvjQ0b5brum2fO08ycne6IrLa0/zvveumqj0/du2E/CyeAtmztDZwN2qualH+K9Hu7BM4lbEkM4PQS2uYWH+ugqOzqfmPZtb+koULGRJb60lT3ONbN74ZVZLVc="
  - secure: "Cl6KV5KKkbYh7eCU6VP2QMOdgdxUPfUJu/YB/IDH1WzdQqXKq/co+Q2Qbw0UvoR5OeBCPIqXdE8wPNLw1mqXhAK3Dg9yOvszELAuHdI4YF5SmfHp+hiaFo/JZLAhl6KOLsE52c0Oe66cAZ+dtcCXT/iyrx/Pkod2v/8oL0FokKJP0nNSU4RZwhtU60t8tflcHckcAyq8kAAVcDviTWFO/M0KhcotikrXVN3gQNcmU+Hf48EXlEiVRcr6QYNfLgcX5QMJQ/b19I90mQAz0yuPdaSQmqSDJKEQErXz+LgnfY9dgEBCWResso6p7NbWxuyKrrQV6wqGTdQ5/G/scTH63BLVIYE4zH9nW0WWDO95DlKS6n0F0Gl7SiUCLVDa+fEihjpIftvPXU4BuSosNb/FE3Xywdoot/Qo7YFJWTCyeq44bv2d3w2mv2vz9OmM+hpqKb0h6+TiekjqwIfXWwYw0bjK/lPWGOmhKRQuPtB5u6S4Mj4TU7BdAzaoDyf/LELMSspEBVrH/t2HrEFrzqe6QVnj9YZDhaexxEEXkmvTL1RIK1Wt2nFAyWglDkzAU6q+f/Mgki5B8ZV8CBxDmLVE9M/jaT+u9g8eA6HWRrViiqnqbeAXTBoEQktjUc9BZ/S/uoctA/eQp3xQCTKbnbQzxbD4X7++kgDrRuXLPrtVk4Q="
before_install:
- composer self-update
install:
- composer install
notifications:
  email:
    recipients:
    - web@mckenziewagner.com
    on_success: always
    on_failure: change
addons:
  firefox: latest
  chrome: stable
