language: php
php:
- '7.2'
mysql:
  database: pantheon
  username: pantheon
  encoding: utf8
env:
  global:
  - MOZ_HEADLESS=1
  - SITE_NAME='McWaffleiron'
  - PSITE='mcwaffleiron'
  - PENV='dev'
  - secure: "jVYByeVf+qs3WjoYXqeNCKwpoMDF1bVRU5fX0I9aSuZ/7ZH/M1u5olwH7n+20CDgDC29SbNMsFwpYFa2ooVngHCfZ/zI51GfyWQe0MA/Y7Em+pQcMnD/NEQLxfukczXI0uTuza8gHcOcBdvoILsX0fWbmLMxVt/7EXuuEiF/lUHIaV1Zsgw3MI4+Xp00XKmrI9nwSAbduvQC+WmFBjtQB1VfN6zgZahuELB6c5GS+L1SWkk6Erqq9sKwHYdByuOb8W3jZPHROCFACqYdimQePsePjLv1ncdw2b4ciM4xJ8bZFH9Sm1e2ERk+AYbxI30/7V9qS0wdKy7kwBozaZm+8ZpcIkdDP2+pY9H5Tr5KX+SPtaGD8F0IcnKDyqKjG0kRJ2gU6kvfENet6pNHt7DJ5xkuSFgp1WKKTgyBPwYzPfGStPgO1fMkUD09yxPpgW3CELHWKrP5NfTc7fL3awBq7Yb3qC9NNwc0NhfbQU6xiijGNJegI/pr+Ty8K2CI+bxCOpNanZ8+DaJ1N2P3ZUl/TIZwceQXmRvjy65bbsHXumq1ojVnBSk+QcEQv0LjV/XsFcSsAr7j2zLyffDnkjA4vr1fnrI8vGF3YrM8PLqRCS/W1dYopD6girCEaW0zUxyHHvaWwJgXGst3dr5kIulNUDKkEjYNYCufYlNC8Fd3dqk="
  - secure: "BfF3LZTnImYtN1Q2Q+ifDTDpwDiwzDoGInND+dnm9nSCtkfi2APZEwAzVScl01UPZ2tk2DiznzY/xUt395TtzqFVC3LrMEJKbQu8qhdaXl3iGSRgwcpMXrEbV4+sQaqDSbyyAiMh77eJan3xwWifsKQGAQIOUF8fIeSxArX2GH0sWBOr2eTQF++75/gGmlau50bfH7tWIJkBgvM7IGxNhOv9nMVA6ApXyzj60WJm24eVs7JJ4UpM5B5r/kV+BQoqcm02adr4OvU5JFJbMVeLxkK9DtZXZx6OSexzot0cDqpkLb+RPU5Mnj7LAhKg6rag/KYvAsaLm7eH7jJDWJmYihZ1kKGS7KSQTlSKAxjIUZ9ZZWH1H+3TTW/3rjVg6E9U3mOrZ1Jeumt0r2LBgRVqIfzbE0KndnL0fCf6mhTWWZBSWrpGN1QtcUjLN7eoBEVcChnxFWtpd8v+ZUuvtq8YjfwB49yZab4hJO4Il6SH4oJwPwFFj/9CegwVdECcN5EpGHJAHVtR9mCs41OWy9pOz4ZqfcvERpoVElz+s6OdPdLWuOn4IsVwVZFRjLEuV7/9GF1S3v49MUlMuQ6MzABdkjOhQWJfL7/he9eoRlDYoJfRDtNv4GACmm5nFmrS8uXQtHW4qnMEE2ybh0v/A9km3IDcxo3PqUjckbsanPuBghY="
  - secure: "EwVWQgJtLPk3zoSL7U9DAiSZLwHHZUOqj3bcMrTbFyd3t+49J+aIEPVQTR22j/i5SZODMhnCJVUBfpS6wilNLRNcAYMFoyrWCIySugisZAGCPB4dYJidMjv38z5/c0jvxsrHBHGoiJSxapf78V4db7ps8ql/zMATVqe0wyGAZf+99xkEF8QV7kKGvvka/rRiL0bzGpxhZru0PMFPDY5T/5bjoZHNsrq/hP8M6WEeSm0bETvN9Br3d6w5mRKhz8THdjrJ+CubzFufhboaLgiNdP0S+Z/jSUdNS11CopiHm1e6V8Zj/Y3GDUkSJOz/Ri1Qc72X4VyN1gTO+g1vmRG7JWM9lE2zq4638un7odadsBOO+/5MkaEXhCH/QesrdN3i18V5hoTNny3dyLNosCMoBUf7irsSmiNnONbIw8LEflu+spARJuWq8z6u7pQqpFvbifd1omfVj2sp8YxDEnM4rhpmqQJi5u+HcZoOolXkLbr8kBK1jSgdGRrB+5P9je0RGWn8+qD8eECnfyPiJbSjKVEq51GHdWazi1YUcOfeN+WWuUGsdPicHsNghdr1Ey0rlrT3UTPaPTreu8B/1mFpc6JKMBbAE9LR5zuQDGk7T6ev9ErVvktbpnDO8kcyHQdrAUcYK0U2Bgfu+AryyDTtAaJICxE1NGC0QDl144izc2M="
before_install:
- composer self-update
install:
- composer install
notifications:
  email:
    recipients:
    - web@mckenziewagner.com
    on_success: always
    on_failure: change
addons:
  firefox: latest
  chrome: stable
